/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siguasystem.facturacionjava;

import com.siguasystem.modelo.Detallefactura;
import com.siguasystem.modelo.DetallefacturaJpaController;
import com.siguasystem.modelo.FacturaJpaController;
import com.siguasystem.modelos.exceptions.NonexistentEntityException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jramos
 */
public class AdministracionX extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdministracionX
     */
    //Conexion JPA
    EntityManagerFactory emFac = Persistence.createEntityManagerFactory("Restorant");
    Tabladetfacx dt = new Tabladetfacx();
    public FacturaJpaController jpfac;
    public DetallefacturaJpaController jpdfac;
    private List<Detallefactura> lsdetfac = new ArrayList<Detallefactura>();
    private Double subtot = 0.0;
    detallefactura dtf = new detallefactura();

    public AdministracionX() {
        initComponents();
        jpdfac = new DetallefacturaJpaController(emFac);
        jpfac = new FacturaJpaController(emFac);
        detfac.setModel(dt.crearTabla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f1 = new com.github.lgooddatepicker.components.DatePicker();
        f2 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detfac = new javax.swing.JTable();
        btnfactmp = new javax.swing.JButton();
        btnfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txttot = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtnlineas = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Fecha Inicial:");

        jLabel2.setText("Fecha Final:");

        detfac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(detfac);

        btnfactmp.setText("Administrar");
        btnfactmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfactmpActionPerformed(evt);
            }
        });

        btnfil.setText("Filtrar");
        btnfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfilActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:");

        txttot.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        txttot.setEnabled(false);
        txttot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setText("Nro. Lineas:");

        txtnlineas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        txtnlineas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnfil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnfactmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnlineas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(f2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtnlineas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnfactmp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfilActionPerformed
        // TODO add your handling code here:
        filFacturasDet();
    }//GEN-LAST:event_btnfilActionPerformed

    private void btnfactmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfactmpActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showInternalConfirmDialog(this, "Esta seguro de Proceder puede perder informacion?", "Precaucion con las Facturas!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int cf = 0;
            int tmpf = 0;
            int fante = 0;
            for (Detallefactura deta : lsdetfac) {
                try {
                    ///Elimina un detalle de las facturas con mas de 2 detalles
                    if (deta.getDetallefacturaPK().getNrolinea() > 1) {
                        if (deta.getPrecio().doubleValue() > 0) {
                            jpdfac.destroy(deta.getDetallefacturaPK());//Eliminacion individual del Detalle       
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(AdministracionX.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        jpdfac.updTotFacturas(f1.toString(), f2.toString());
        JOptionPane.showInternalConfirmDialog(this, "La informacion fue actualizada.", "Precaucion verificar las Facturas!", JOptionPane.YES_OPTION);
        /*try {
                jpdfac.delDetFacturas(f1.toString(), f2.toString(),Integer.parseInt(txtnlineas.getValue().toString()));
                //jpdfac.updTotFacturas(f1.toString(), f2.toString());
                JOptionPane.showInternalConfirmDialog(this, "La informacion fue actualizada.", "Precaucion verificar las Facturas!", JOptionPane.YES_OPTION);
            } catch (Exception e) {
                System.out.println("Error->"+e.getMessage());
            }
            }*/

    }//GEN-LAST:event_btnfactmpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            jpdfac.updTotFacturas(f1.toString(), f2.toString());
            JOptionPane.showInternalConfirmDialog(this, "La informacion fue actualizada.", "Precaucion verificar las Facturas!", JOptionPane.YES_OPTION);
        } catch (Exception e) {
            System.out.println("Error->" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void filFacturasDet() {
        //Carga el detalle existente
        lsdetfac = jpdfac.findDetallefacturaFechasPreNlineas(f1.toString(), f2.toString());
        addproTable2(lsdetfac);
        //System.out.println(""+lsdetfac);      
    }

    public void addproTable2(List<Detallefactura> ldet) {
        DefaultTableModel temp = (DefaultTableModel) detfac.getModel();
        detfac.setModel(temp);
        Double totFac = 0.0;
        for (Detallefactura deta : ldet) {
            articulo padd = new articulo();
            padd.setId(deta.getDetallefacturaPK().getNrolinea());
            padd.setCodigo(deta.getProducto());
            padd.setNombre(deta.getNomproducto());
            padd.setPrecio(deta.getPrecio());
            padd.setCantidad(deta.getCantidad());
            padd.setComentarios(deta.getComentarios());
            //boolean x=(deta.getIsv().doubleValue()>0)?true:false;
            padd.setIsv((deta.getIsv().doubleValue() > 0) ? true : false);
            padd.setDescuento(deta.getDescuento().doubleValue());
            padd.setValisv(deta.getIsv().doubleValue());
            subtot = (deta.getIsv().doubleValue() + deta.getPrecio().doubleValue()) * deta.getCantidad();
            padd.setSubtotal(subtot);
            padd.setEstado(deta.getStadodet().toString());
            dtf.addPArticulos(padd);
            try {
                Object nuevo[] = {padd.getId(), deta.getDetallefacturaPK().getIdFactura(), padd.getCodigo(), padd.getNombre(), padd.getComentarios(), String.format("%,.2f", padd.getCantidad()),
                    String.format("%,.2f", padd.getPrecio()), String.format("%,.2f", padd.getDescuento()), String.format("%,.2f", padd.getValisv()), String.format("%,.2f", padd.getSubtotal())};
                temp.addRow(nuevo);
                totFac += (padd.getCantidad()*padd.getPrecio().doubleValue())-padd.getValisv();
            } catch (Exception e) {
                System.out.println("" + e.getMessage());
            }
        }
        txttot.setValue(totFac);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfactmp;
    private javax.swing.JButton btnfil;
    private javax.swing.JTable detfac;
    private com.github.lgooddatepicker.components.DatePicker f1;
    private com.github.lgooddatepicker.components.DatePicker f2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner txtnlineas;
    private javax.swing.JSpinner txttot;
    // End of variables declaration//GEN-END:variables
}
