/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siguasystem.facturacionjava;

import com.siguasystem.modelo.ClienteJpaController;
import com.siguasystem.modelo.Producto;
import com.siguasystem.modelo.ProductoJpaController;
import com.siguasystem.modelo.exceptions.NonexistentEntityException;
import java.math.BigDecimal;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import modeloold.ClientesJpaController;
import modeloold.Productoold;
import modeloold.ProductooldJpaController;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
       
/**
 *
 * @author jramos
 */
public class migrarInformacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form migrarInformacion
     */
    EntityManagerFactory emold = Persistence.createEntityManagerFactory("sisold");
    EntityManagerFactory em = Persistence.createEntityManagerFactory("Restorant");
    ClientesJpaController jpcliold = new ClientesJpaController(emold);
    ClienteJpaController jpcli = new ClienteJpaController(em);
    ProductoJpaController jpnew=new ProductoJpaController(em);
    ProductooldJpaController jpold=new ProductooldJpaController(emold);

    public migrarInformacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncli = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        btncli.setText("Migrar Clientes");
        btncli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncliActionPerformed(evt);
            }
        });

        jButton1.setText("Migrar Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btncli, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncli, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addContainerGap(355, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncliActionPerformed
        // TODO add your handling code here:
        int entityCount = 50;
        int batchSize = 25;

        EntityManager entityManager =jpcli.getEntityManager();

        EntityTransaction entityTransaction = entityManager
                .getTransaction();

        try {
            entityTransaction.begin();
            for (int i = 0; i < entityCount; i++) {
                if (i > 0 && i % batchSize == 0) {
                    entityTransaction.commit();
                    entityTransaction.begin();
                    entityManager.clear();
                }
                entityManager.persist(evt);
            }

            entityTransaction.commit();
        } catch (RuntimeException e) {
            if (entityTransaction.isActive()) {
                entityTransaction.rollback();
            }
            throw e;
        } finally {
            entityManager.close();
        }
    }//GEN-LAST:event_btncliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<Producto> lp=jpnew.findProductoEntities();
        for (Producto p : lp) {
            try {
                jpnew.destroy(p.getIdProducto());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(migrarInformacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        List<Productoold> pold=jpold.findProductoEntities(50, 1);
        for (Productoold po : pold) {
            try {
                Producto p=new Producto();
                p.setIdProducto(po.getIdProducto());
                p.setNombre(po.getNombre());
                p.setPrecio(po.getPrecio());
                p.setCategoria(po.getCategoria());
                p.setImpuesto(BigDecimal.valueOf(0.00));
                p.setCantidadexis(0);
                jpnew.create(p);
            } catch (Exception ex) {
                Logger.getLogger(migrarInformacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncli;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
